/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.tss.wincalcio;

import static it.tss.wincalcio.WinDialogPartite.listapartite;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tss
 */
public class WinCalcio extends javax.swing.JFrame {

    static List<Squadra> listasquadre = new ArrayList<>();

    /**
     * Creates new form WinCalcio
     */
    public WinCalcio() {
        initComponents();
        this.setLocationRelativeTo(null);
        caricaSquadre();
        caricaPartite();
        caricaClassifica();
        refreshTable();
        lblMsg.setText("Inserisci o modifica dati squadra");
        Color col = new Color(85, 182, 63);
        this.getContentPane().setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        txSede = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblElencoSq = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        btnPrepare = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnGestionePartite = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnClassifiche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIONE SQUADRE");

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setText("Squadra");

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel4.setText("Sede:");

        tblElencoSq.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        tblElencoSq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Sede"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblElencoSq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblElencoSqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblElencoSq);

        btnConfirm.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(5, 87, 1));
        btnConfirm.setText("Conferma dati");
        btnConfirm.setPreferredSize(new java.awt.Dimension(100, 30));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnPrepare.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnPrepare.setText("Prepara dati");
        btnPrepare.setPreferredSize(new java.awt.Dimension(100, 30));
        btnPrepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepareActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(1, 1, 1));

        btnDelete.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 23, 6));
        btnDelete.setText("Elimina");
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnClose.setText("Chiudi");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnGestionePartite.setText("Vai a Gestione Partite");
        btnGestionePartite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionePartiteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 1, 28)); // NOI18N
        jLabel5.setText("CALCIO");

        jLabel6.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel6.setText("Elenco Squadre");

        btnClassifiche.setText("Vai a Classifiche Partite");
        btnClassifiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txSede)
                                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnPrepare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClassifiche, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(btnGestionePartite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrepare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnGestionePartite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClassifiche, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_formWindowActivated

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        String nmsq = txNome.getText();
        String nmsede = txSede.getText();
        Squadra sq = new Squadra(nmsq, nmsede);
        if (tblElencoSq.getSelectedRow() == -1) {
            listasquadre.add(sq);
            lblMsg.setText("Squadra aggiunta correttamente!");
        } else {
            int index = tblElencoSq.getSelectedRow();
            listasquadre.set(index, sq);
        }
        pulisci();
        salvaCSVSq();
        refreshTable();
        tblElencoSq.clearSelection();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnPrepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepareActionPerformed
        // TODO add your handling code here:
        pulisci();
        lblMsg.setText("Inserisci i dati della squadra");
        tblElencoSq.clearSelection();
    }//GEN-LAST:event_btnPrepareActionPerformed

    private void tblElencoSqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblElencoSqMouseClicked
        // TODO add your handling code here:
        int index = tblElencoSq.getSelectedRow();
        txNome.setText((listasquadre.get(index).getNome()));
        txSede.setText(listasquadre.get(index).getSede());
    }//GEN-LAST:event_tblElencoSqMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tblElencoSq.getSelectedRow();
        if (index == -1) {
            return;
        }
        int input = JOptionPane.showConfirmDialog(null,
                "Confermi l'eliminazione?", "ELIMINA Squadra", JOptionPane.OK_CANCEL_OPTION);
        if (input == 0) {
            listasquadre.remove(index);
            salvaCSVSq();
            refreshTable();
            pulisci();
            lblMsg.setText("Squadra eliminata correttamente");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnGestionePartiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionePartiteActionPerformed
        // TODO add your handling code here:
        new WinDialogPartite(this, true).setVisible(true);
    }//GEN-LAST:event_btnGestionePartiteActionPerformed

    private void btnClassificheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificheActionPerformed
        // TODO add your handling code here:
        new WinDialogClassifica(this, true).setVisible(true);
    }//GEN-LAST:event_btnClassificheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinCalcio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassifiche;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGestionePartite;
    private javax.swing.JButton btnPrepare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JTable tblElencoSq;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txSede;
    // End of variables declaration//GEN-END:variables

    private void caricaSquadre() {
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            File filecsv = new File(pf + "/Calcio/squadre.csv");
            Scanner lettore = new Scanner(filecsv);
            boolean primariga = true;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (!primariga) {
                    String[] dati = riga.split(";");
                    String nmsq = dati[0];
                    String nmsede = dati[1];
                    Squadra sq = new Squadra(nmsq, nmsede);
                    listasquadre.add(sq);
                }
                primariga = false;
            }

        } catch (Exception e) {

        }

    }

    private void caricaPartite() {
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            File filecsv = new File(pf + "/Calcio/partite.csv");
            Scanner lettore = new Scanner(filecsv);
            boolean primariga = true;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (!primariga) {
                    String[] dati = riga.split(";");
                    int g = Integer.parseInt(dati[0]);
                    String nsq1 = dati[1];
                    String nsq2 = dati[2];
                    int gol1 = Integer.parseInt(dati[3]);
                    int gol2 = Integer.parseInt(dati[4]);
                    Partita pt = new Partita(g, nsq1, nsq2, gol1, gol2);
                    listapartite.add(pt);
                }
                primariga = false;
            }

        } catch (Exception e) {

        }
    }
    
    private void caricaClassifica(){
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            File filecsv = new File(pf + "/Calcio/classifica.csv");
            Scanner lettore = new Scanner(filecsv);
            boolean primariga = true;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (!primariga) {
                    String[] dati = riga.split(";");
                    String sq = dati[0];
                    int p = Integer.parseInt(dati[1]);
                    Classifica cl = new Classifica(sq, p);
                    WinDialogPartite.classifica.add(cl);
                }
                primariga = false;
            }

        } catch (Exception e) {

        }
    }

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblElencoSq.getModel();
        model.setRowCount(0);
        int ncol = model.getColumnCount();
        Object[] rowData = new Object[ncol];
        for (Squadra sq : listasquadre) {
            rowData[0] = sq.getNome();
            rowData[1] = sq.getSede();
            model.addRow(rowData);
        }
    }

    private void pulisci() {
        txNome.setText("");
        txSede.setText("");
    }

    private void salvaCSVSq() {
        String intestazione = "nome;sede\n";
        String dati = "";
        for (int i = 0; i < listasquadre.size(); i++) {
            Squadra sq = listasquadre.get(i);
            String riga = sq.getCSVSq();
            dati += riga;
        }
        String txfile = intestazione + dati;
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            FileWriter myWriter = new FileWriter(pf + "/Calcio/squadre.csv");
            myWriter.write(txfile);
            myWriter.close();
        } catch (Exception e) {
            lblMsg.setText("Errore di scrittura file squadre.csv");
        }
    }

}
