/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package it.tss.wincalcio;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static it.tss.wincalcio.WinCalcio.listasquadre;

/**
 *
 * @author tss
 */
public class WinDialogPartite extends javax.swing.JDialog {

    static List<Partita> listapartite = new ArrayList<>();
    static List<Classifica> classifica = new ArrayList<>();

    /**
     * Creates new form WinDialogPartite
     */
    public WinDialogPartite(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        spGiornata.setValue(1);
        refreshTable();
        lblMsg.setText("Inserisci o modifica dati partita");
        Color col = new Color(252, 100, 86);
        this.getContentPane().setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txSquadra2 = new javax.swing.JTextField();
        txSquadra1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartite = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnPrepare = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spGol1 = new javax.swing.JSpinner();
        spGol2 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        spGiornata = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel4.setText("Squadra1:");

        tblPartite.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        tblPartite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Giornata", "Squadra1", "Squadra2", "Gol1", "Gol2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPartite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPartiteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPartite);

        btnClose.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnClose.setText("Chiudi");
        btnClose.setPreferredSize(new java.awt.Dimension(100, 30));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(0, 157, 3));
        btnConfirm.setText("Conferma dati");
        btnConfirm.setPreferredSize(new java.awt.Dimension(100, 30));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnPrepare.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnPrepare.setText("Prepara dati");
        btnPrepare.setPreferredSize(new java.awt.Dimension(100, 30));
        btnPrepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepareActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(239, 23, 6));
        btnDelete.setText("Elimina");
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIONE PARTITE");

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setText("Partita");

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        jLabel3.setText("Giornata:");

        jLabel5.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel5.setText("Squadra2:");

        jLabel6.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel6.setText("Gol1:");

        jLabel7.setFont(new java.awt.Font("URW Gothic L", 0, 15)); // NOI18N
        jLabel7.setText("Gol2:");

        jLabel8.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel8.setText("Elenco Partite");

        lblMsg.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrepare, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spGol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spGol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(282, 282, 282)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spGol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spGol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrepare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPartiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPartiteMouseClicked
        // TODO add your handling code here:
        int index = tblPartite.getSelectedRow();
        spGiornata.setValue(listapartite.get(index).getGiornata());
        txSquadra1.setText(listapartite.get(index).getSquadra1());
        txSquadra2.setText(listapartite.get(index).getSquadra2());
        spGol1.setValue(listapartite.get(index).getGol1());
        spGol2.setValue(listapartite.get(index).getGol2());
    }//GEN-LAST:event_tblPartiteMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        int g = Integer.parseInt(String.valueOf(spGiornata.getValue()));
        String sq1 = txSquadra1.getText();
        String sq2 = txSquadra2.getText();
        int gol1 = Integer.parseInt(String.valueOf(spGol1.getValue()));
        int gol2 = Integer.parseInt(String.valueOf(spGol2.getValue()));
        Partita pt = new Partita(g, sq1, sq2, gol1, gol2);
        if (tblPartite.getSelectedRow() == -1 && verifica(sq1, sq2)) {
            listapartite.add(pt);
            Squadra squadra1 = new Squadra();
            int p1 = squadra1.punteggio(sq1);
            Squadra squadra2 = new Squadra();
            int p2 = squadra2.punteggio(sq2);
            Classifica cl1 = new Classifica(sq1, p1);
            Classifica cl2 = new Classifica(sq2, p2);
            classifica.add(cl1);
            classifica.add(cl2);
            lblMsg.setText("Partita aggiunta correttamente!");
        } else if (tblPartite.getSelectedRow() != -1 && verifica(sq1, sq2)) {
            int index = tblPartite.getSelectedRow();
            Squadra squadra1 = new Squadra();
            int p1 = squadra1.punteggio(sq1);
            Squadra squadra2 = new Squadra();
            int p2 = squadra2.punteggio(sq2);
            Classifica cl1 = new Classifica(sq1, p1);
            Classifica cl2 = new Classifica(sq2, p2);
            classifica.add(cl1);
            classifica.add(cl2);
            listapartite.set(index, pt);
            lblMsg.setText("Partita aggiornata correttamente!");
        } else if (!verifica(sq1, sq2)) {
            lblMsg.setText("Una o più squadre inserite non sono presenti nell'elenco squadre");
            return;
        }

        pulisci();
        salvaCSVPt();
        salvaCSVClass();
        classifica.clear();
        refreshTable();
        tblPartite.clearSelection();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnPrepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepareActionPerformed
        // TODO add your handling code here:
        pulisci();
        lblMsg.setText("Inserisci i dati della partita");
        tblPartite.clearSelection();
    }//GEN-LAST:event_btnPrepareActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tblPartite.getSelectedRow();
        if (index == -1) {
            return;
        }
        int input = JOptionPane.showConfirmDialog(null,
                "Confermi l'eliminazione?", "ELIMINA Partita", JOptionPane.OK_CANCEL_OPTION);
        if (input == 0) {
            listapartite.remove(index);
            salvaCSVPt();
            salvaCSVClass();
            refreshTable();
            pulisci();
            lblMsg.setText("Partita eliminata correttamente");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinDialogPartite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinDialogPartite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinDialogPartite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinDialogPartite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinDialogPartite dialog = new WinDialogPartite(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrepare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JSpinner spGiornata;
    private javax.swing.JSpinner spGol1;
    private javax.swing.JSpinner spGol2;
    private javax.swing.JTable tblPartite;
    private javax.swing.JTextField txSquadra1;
    private javax.swing.JTextField txSquadra2;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblPartite.getModel();
        model.setRowCount(0);
        int ncol = model.getColumnCount();
        Object[] rowData = new Object[ncol];
        for (Partita pt : listapartite) {
            rowData[0] = pt.getGiornata();
            rowData[1] = pt.getSquadra1();
            rowData[2] = pt.getSquadra2();
            rowData[3] = pt.getGol1();
            rowData[4] = pt.getGol2();
            model.addRow(rowData);
        }
    }

    private void pulisci() {
        spGiornata.setValue(1);
        txSquadra1.setText("");
        txSquadra2.setText("");
        spGol1.setValue(0);
        spGol2.setValue(0);
        tblPartite.clearSelection();
    }

    private void salvaCSVPt() {
        String intestazione = "giornata;squadra1;squadra2;gol1;gol2\n";
        String dati = "";
        for (int i = 0; i < listapartite.size(); i++) {
            Partita pt = listapartite.get(i);
            String riga = pt.getCSVPartita();
            dati += riga;
        }
        String txfile = intestazione + dati;
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            FileWriter myWriter = new FileWriter(pf + "/Calcio/partite.csv");
            myWriter.write(txfile);
            myWriter.close();
        } catch (Exception e) {
            lblMsg.setText("Errore di scrittura file partite.csv");
        }
    }

    private void salvaCSVClass() {
        String intestazione = "squadra;punteggio\n";
        String dati = "";
        for (int i = 0; i < classifica.size(); i++) {
            Classifica cl = classifica.get(i);
            String riga = cl.getCSVClass();
            dati += riga;
        }
        String txfile = intestazione + dati;
        try {
            File fi = new File("");
            String pf = fi.getCanonicalPath();
            FileWriter myWriter = new FileWriter(pf + "/Calcio/classifica.csv");
            myWriter.write(txfile);
            myWriter.close();
        } catch (Exception e) {
            lblMsg.setText("Errore di scrittura file classifica.csv");
        }
    }

    private boolean verifica(String nomesq1, String nomesq2) {
        boolean ris = false;
        for (Squadra sq : listasquadre) {
            if (nomesq1.equals(sq.getNome())) {
                for (Squadra sq2 : listasquadre) {
                    if (nomesq2.equals(sq2.getNome())) {
                        ris = true;
                    }

                }
            }
        }
        return ris;

    }

}
