/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionesquadra;

import java.io.File;
import java.io.FileWriter;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tss
 */
public class WinCalcio extends javax.swing.JFrame {

    static ArrayList<Squadra> Eleconcosq = new ArrayList<Squadra>();
    static ArrayList<Partita> Elencopa = new ArrayList<Partita>();
    static ArrayList<Classifica> Class = new ArrayList<Classifica>();

    Integer punteggio;

    /**
     * Creates new form WinCalcio
     */
    public WinCalcio() {
        initComponents();
        caricaDatiSquadra();
        caricaDatiPartita();
        refreshLista();
        refreshListaA();
        refreshTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPartita = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        txNomeSquadra = new javax.swing.JTextField();
        txSede = new javax.swing.JTextField();
        btnCreaSquadra = new javax.swing.JButton();
        lblTitolo = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSquadra = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdatesquadra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txGiornata = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txSquadra1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txSquadra2 = new javax.swing.JTextField();
        txGol1 = new javax.swing.JTextField();
        txGol2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCreaPartita = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsquadra = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Sede Squadra");

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.blue);
        jLabel7.setText("Lista squadre");

        btnClose.setForeground(java.awt.Color.black);
        btnClose.setText("Chiudi");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstPartita);

        jLabel8.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.blue);
        jLabel8.setText("Elenco partite");

        txNomeSquadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeSquadraActionPerformed(evt);
            }
        });

        txSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSedeActionPerformed(evt);
            }
        });

        btnCreaSquadra.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        btnCreaSquadra.setForeground(java.awt.Color.red);
        btnCreaSquadra.setText("Conferma dati");
        btnCreaSquadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaSquadraActionPerformed(evt);
            }
        });

        lblTitolo.setFont(new java.awt.Font("Bitstream Charter", 3, 24)); // NOI18N
        lblTitolo.setForeground(java.awt.Color.blue);
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione Calcio");
        lblTitolo.setAlignmentX(0.5F);

        lblMsg.setForeground(java.awt.Color.red);

        lstSquadra.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        lstSquadra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstSquadraKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(lstSquadra);

        jLabel1.setText("Nome Squadra");

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.magenta);
        jLabel4.setText("squadra");

        btnUpdatesquadra.setForeground(java.awt.Color.red);
        btnUpdatesquadra.setText("Update");
        btnUpdatesquadra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatesquadraActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.magenta);
        jLabel3.setText("Partita");

        txGiornata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGiornataActionPerformed(evt);
            }
        });

        jLabel5.setText("giornata");

        jLabel6.setText("squadra1");

        jLabel9.setText("squadra2");

        txGol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txGol2ActionPerformed(evt);
            }
        });

        jLabel10.setText("gol1");

        jLabel11.setText("gol2");

        btnCreaPartita.setForeground(java.awt.Color.red);
        btnCreaPartita.setText("Crea Partita");
        btnCreaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreaPartitaActionPerformed(evt);
            }
        });

        tblsquadra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "squadra", "punti", "fatti", "subiti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsquadra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsquadraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblsquadra);

        jLabel12.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        jLabel12.setForeground(java.awt.Color.blue);
        jLabel12.setText("classifica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdatesquadra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(341, 341, 341))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnCreaSquadra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(257, 257, 257)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txSquadra2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txGol1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                        .addComponent(txGol2)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(238, 238, 238)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txNomeSquadra, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(txSede)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(443, 443, 443)))
                    .addContainerGap(256, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(109, 109, 109)
                .addComponent(btnCreaSquadra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdatesquadra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(btnClose)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txGiornata, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txSquadra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txSquadra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txGol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txGol2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreaPartita)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txNomeSquadra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txNomeSquadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeSquadraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeSquadraActionPerformed

    private void txSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSedeActionPerformed

    private void btnCreaSquadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaSquadraActionPerformed

        //Recuperiamo i dati da interfaccia
        String ns = txNomeSquadra.getText();
        String sede = txSede.getText();

        Squadra sq = new Squadra(ns, sede);

        Eleconcosq.add(sq);
        salvaSquadra();
        salvaSquadraCSV();
        refreshLista();

    }//GEN-LAST:event_btnCreaSquadraActionPerformed
    private void caricaDatiSquadra() {
        try {
            //aprire il file /tss/Scuola/dati.csv
            File filecsv = new File("/home/tss/Squadre/squadra.csv");
            //creo scanner per leggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            boolean primariga = true;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (!primariga) {
                    String[] dati = riga.split(";");
                    //dati[0] nomecorso dati[1] durata etc...

                    String nome = dati[0];
                    String sede = dati[1];

                    Squadra s = new Squadra(nome, sede);

                    Eleconcosq.add(s);
                }
                primariga = false;
            }
            //righe del file
            //alla fine chiudo il file se no si blocca
        } catch (Exception e) {

        }
    }

    private void caricaDatiPartita() {
        try {
            //aprire il file /tss/Scuola/dati.csv
            File filecsv = new File("/home/tss/Squadre/squadra.csv");
            //creo scanner per leggere una riga per volta
            Scanner lettore = new Scanner(filecsv);
            //estrarre una riga per volta
            boolean primariga = true;
            while (lettore.hasNextLine()) {
                String riga = lettore.nextLine();
                if (!primariga) {
                    String[] dati = riga.split(";");
                    //dati[0] nomecorso dati[1] durata etc...

                    String squadra1 = dati[0];
                    String squadra2 = dati[1];
                    int gol1 = Integer.parseInt(dati[2]);
                    int gol2 = Integer.parseInt(dati[3]);
                    int giornata = Integer.parseInt(dati[4]);

                    Partita p = new Partita(squadra1, squadra2, gol1, gol2, giornata);

                    Elencopa.add(p);
                }
                primariga = false;
            }
            //righe del file
            //alla fine chiudo il file se no si blocca
        } catch (Exception e) {

        }
    }

    private void refreshLista() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < Eleconcosq.size(); i++) {
            String nc = Eleconcosq.get(i).getNome_squadra();
            model.addElement(nc);
        }
        lstSquadra.setModel(model);

    }

    private void salvaSquadraCSV() {
        // recupero un corso per volta
        // estraggo info tipo String
        // aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "nomesquadra;sede\n";
        for (int i = 0; i < Eleconcosq.size(); i++) {
            // recupero un corso per volta
            Squadra sq = Eleconcosq.get(i);
            String info = sq.getCSVInfo();
            testoDisplay += info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Squadra/squadre.csv");
            myWriter.write(testoDisplay);
            // ci scrivo dentro testoDisplay
            // lo chiudo se no si blocca
            myWriter.close();
        } catch (Exception e) {

        }
    }

    private void salvaSquadra() {

        // aggiungo info a un testo generico che poi setto in displaysiCSV();
        String testoDisplay = "";
        for (int i = 0; i < Eleconcosq.size(); i++) {
            // recupero un prodotto per volta
            Squadra sq = Eleconcosq.get(i); //get(i) sarebbe listacorsi[i] in un array normale;
            String info = sq.getInfo();
            testoDisplay += info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Squadra/squadre.txt");
            myWriter.write(testoDisplay);
            // ci scrivo dentro testoDisplay
            // lo chiudo se no si blocca
            myWriter.close();
        } catch (Exception e) {

        }
    }
    private void lstSquadraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstSquadraKeyPressed

    }//GEN-LAST:event_lstSquadraKeyPressed

    private void txGol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGol2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txGol2ActionPerformed

    private void btnCreaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreaPartitaActionPerformed

        //Recuperiamo i dati da interfaccia
        String sq1 = txSquadra1.getText();
        String sq2 = txSquadra2.getText();
        String sgol1 = txGol1.getText();
        String sgol2 = txGol2.getText();
        String sgiornata = txGiornata.getText();
        int gol1 = Integer.parseInt(sgol1);
        int gol2 = Integer.parseInt(sgol2);
        int giornata = Integer.parseInt(sgiornata);

        Partita pa = new Partita(sq1, sq2, gol1, gol2, giornata);

        Elencopa.add(pa);
        salvaPartita();
        salvaPartitaCSV();
        refreshListaA();

    }

    private void refreshListaA() {
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < Elencopa.size(); i++) {
            Partita p = Elencopa.get(i);
            String np = p.getGiornata() + "-" + p.getSquadra1() + "-" + p.getSquadra2() + "-" + p.getGol1() + "-" + p.getGol2();
            model.addElement(np);
        }
        lstPartita.setModel(model);


    }//GEN-LAST:event_btnCreaPartitaActionPerformed
    private void refreshTable() {
        // recuperare la struttura dati della mia tabella come model
        DefaultTableModel model = (DefaultTableModel) tblsquadra.getModel();
        //pulire la tabella dai dati precedenti setto la dimensione row a zero
        model.setRowCount(0);
        int ncol = model.getColumnCount();
        Object[] rowData = new Object[ncol];
        for (Classifica c : Class) {
            //assegno ai 3 elementi dell'array il contenuto equivalente di colonna
            rowData[0] = c.getNome_squadra();
            rowData[1] = c.getPunti();
            rowData[2] = c.getFatti();
            rowData[3] = c.getSubiti();

        }

    }
    private void btnUpdatesquadraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatesquadraActionPerformed
        String ns = txNomeSquadra.getText();
        String sede = txSede.getText();

        Squadra newsquadra = new Squadra(ns, sede);

        if (lstSquadra.getSelectedIndex() == -1) { //nessuna selezione, non sono in modifica
            Eleconcosq.add(newsquadra);
            lblMsg.setText("Squadra creata correttamente!");
        } else { //lista selezionata sono in modifica dell'iesimo elemento
            Eleconcosq.set(lstSquadra.getSelectedIndex(), newsquadra);
            lblMsg.setText("Squadra aggiornata correttamente!");
        }
        txNomeSquadra.setText("");
        txSede.setText("");

        lstSquadra.setSelectedIndex(-1);
        refreshLista();
        //mostra elenco aggiornato in display di listacorsi
        salvaSquadra();
        salvaSquadraCSV();
        validaSquadra();

    }//GEN-LAST:event_btnUpdatesquadraActionPerformed

    private void txGiornataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txGiornataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txGiornataActionPerformed

    private void tblsquadraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsquadraMouseClicked
        int index = tblsquadra.getSelectedRow();

        JOptionPane.showMessageDialog(null, Class.get(index).getInfoClass());

    }//GEN-LAST:event_tblsquadraMouseClicked

    private boolean validaSquadra() {
        boolean ret = false;

        boolean okNome = !txNomeSquadra.getText().equals("");
        boolean okSede = !txSede.getText().equals("");

        if (okNome && okSede) {
            ret = true;
        }
        return ret;
    }

    private void salvaPartitaCSV() {
        // recupero un corso per volta
        // estraggo info tipo String
        // aggiungo info a un testo generico che poi setto in display
        String testoDisplay = "g;incasa;trsaferta;gol1;gol2\n";
        for (int i = 0; i < Elencopa.size(); i++) {
            // recupero un corso per volta
            Partita pa = Elencopa.get(i);
            String info = pa.getCSVInfo();
            testoDisplay += info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Partita/partita.csv");
            myWriter.write(testoDisplay);
            // ci scrivo dentro testoDisplay
            // lo chiudo se no si blocca
            myWriter.close();
        } catch (Exception e) {

        }
    }

    private void salvaPartita() {

        // aggiungo info a un testo generico che poi setto in displaysiCSV();
        String testoDisplay = "";
        for (int i = 0; i < Elencopa.size(); i++) {
            // recupero un prodotto per volta
            Partita pa = Elencopa.get(i); //get(i) sarebbe listacorsi[i] in un array normale;
            String info = pa.getInfo();
            testoDisplay += info;
        }
        try {
            // creo file corsi.txt
            FileWriter myWriter = new FileWriter("/home/tss/Partita/partita.txt");
            myWriter.write(testoDisplay);
            // ci scrivo dentro testoDisplay
            // lo chiudo se no si blocca
            myWriter.close();
        } catch (Exception e) {

        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCalcio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinCalcio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreaPartita;
    private javax.swing.JButton btnCreaSquadra;
    private javax.swing.JButton btnUpdatesquadra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JList<String> lstPartita;
    private javax.swing.JList<String> lstSquadra;
    private javax.swing.JTable tblsquadra;
    private javax.swing.JTextField txGiornata;
    private javax.swing.JTextField txGol1;
    private javax.swing.JTextField txGol2;
    private javax.swing.JTextField txNomeSquadra;
    private javax.swing.JTextField txSede;
    private javax.swing.JTextField txSquadra1;
    private javax.swing.JTextField txSquadra2;
    // End of variables declaration//GEN-END:variables
}
